# Generated by Django 4.0.3 on 2022-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
