# Generated by Django 4.0.3 on 2022-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default='2015-08-23 11:34:30'),
            preserve_default=False,
        ),
    ]
