# Generated by Django 4.0.3 on 2022-04-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_video_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
