# Generated by Django 4.0.3 on 2022-04-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
    ]
