# Generated by Django 4.0.3 on 2022-04-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_video_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
