# Generated by Django 4.0.3 on 2022-04-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_video_active_video_file_type_video_path_video_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='active',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded',
        ),
    ]
