# Generated by Django 4.0.3 on 2022-04-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_video_active_remove_video_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
